# Set the base image to Ubuntu
FROM mhart/alpine-node:4.4.3

# File Author / Maintainer
MAINTAINER Ben Coe

COPY ./replicated/policy-follower/start.sh /etc/npme/start.sh
COPY ./replicated/policy-follower/add-package.sh /etc/npme/add-package.sh
COPY ./replicated/policy-follower/remove-package.sh /etc/npme/remove-package.sh
COPY ./replicated/policy-follower/reset-follower.sh /etc/npme/reset-follower.sh
WORKDIR /etc/npme

RUN echo '@npm:registry=https://enterprise.npmjs.com/' > ~/.npmrc
RUN npm install @npm/policy-follower@travis
RUN npm install @npm/package-whitelist
RUN apk update
RUN apk add curl
RUN rm -rf /var/cache/apk/*

CMD ["/etc/npme/start.sh"]
