# Set the base image to Ubuntu
FROM mhart/alpine-node:4.3.1

# File Author / Maintainer
MAINTAINER Ben Coe

COPY ./replicated/start.sh /etc/npme/start.sh
WORKDIR /etc/npme

RUN echo '@npm:registry=https://enterprise.npmjs.com/' > ~/.npmrc
RUN npm install npm-registry-couchapp@npmo
RUN npm install @npm/registry-frontdoor@2.7.1
RUN apk update
RUN apk add curl
RUN apk add bash
RUN rm -rf /var/cache/apk/*

EXPOSE 8080

CMD ["/etc/npme/start.sh"]
